server:
  port: 8080

security:
  oauth2:
    client:
      client-id: client-one
      client-secret: client-one-secret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token

logging.level:
  org.springframework: DEBUG

zuul:
  routes:
    front:
      path: /api/**
      url: http://localhost:8090