server:
  port: 8090
#  context-path: /api

#security:
#  oauth2:
#    client:
#      client-id: client-one
#      client-secret: client-one-secret
#      access-token-uri: http://localhost:9999/uaa/oauth/token
#      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
#    resource:
#      token-info-uri: http://localhost:9999/uaa/oauth/check_token

security:
  oauth2:
    client:
      client-id: resource-server
      client-secret: resource-server-secret
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token

logging.level:
  org.springframework: DEBUG