server:
  port: 8082

security:
  oauth2:
    client:
      client-id: resource-server
      client-secret: resource-server-secret
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token
